name: Feature request
description: Suggest an idea for this project.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the problem, not just the solution you have in mind.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
  - type: textarea
    id: context
    attributes:
      label: Anything else?
      description: Screenshots, examples, or links to how other projects handle it.
